force-app/main/default/objects/Order_Items__c/Order_Items__c.object-meta.xml
<CustomObject>
    <label>Order_Items</label>
    <nameField>
        <label>Order_Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order_Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Items__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Order_Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Reserved_Stock__c.field-meta.xml
<CustomField>
    <fullName>Reserved_Stock__c</fullName>
    <label>Reserved Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Stock_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Stock_Quantity__c</fullName>
    <label>Stock_Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/C_OrderItemsTrigger_handler.cls
public class C_OrderItemsTrigger_handler {
	
    public static void validateStock(List<Order_Items__c> orderItems){
        
       	Set<Id> productIds = new Set<Id>();
        for(Order_Items__c orderItem: orderItems){
            if(orderItem.Product__c!=null){
                productIds.add(orderItem.Product__c); // storing reference of all product associated with orderItem
            }
        }
        System.debug('product id added');
        
       	// Search all products associated with productIds
        Map<Id,Product__c> productsMap = new Map<Id,Product__c>(
        [select Id, Name, Stock_Quantity__c, Reserved_Stock__c from Product__c where Id In: productIds]
        );
        
        System.debug(productsMap);
        
        // validate stock 
        for(Order_Items__c orderItem: orderItems){
            if(orderItem.Product__c!=null && productsMap.containsKey(orderItem.Product__c)){
                Product__c product = productsMap.get(orderItem.Product__c); // fetch product associated with orderItem
                Integer reservedStock = (Integer)(product.Reserved_Stock__c != null ? product.Reserved_Stock__c : 0); // initially reverseStock will be null to handle that case

                Integer availableQyt = (Integer)(product.Stock_Quantity__c - reservedStock); // actual available quantity
                if(availableQyt<orderItem.Quantity__c){ 
                    orderItem.addError('Not enough quantity for product:'+product.Name);
                }
            }
        }
        
    }
    
    public static void reserveStock(List<Order_Items__c> orderItems){
        Map<Id,Integer> productQytMap = new Map<Id,Integer>();
        
        for(Order_Items__c orderItem: orderItems){
            if(orderItem.Product__c!=null ){
                if(!productQytMap.containsKey(orderItem.Product__c)){
                    productQytMap.put(orderItem.Product__c,0); // initially product reserveStock is 0
                }
                productQytMap.put(orderItem.Product__c,(Integer)(productQytMap.get(orderItem.Product__c)+orderItem.Quantity__c)); //store reserve stock for each product
            }
        }
        //Update Inventory
        System.debug('Before updating inventory:'+productQytMap);
        C_OrderItemsTrigger_Inventory.reserveStock(productQytMap);
        
    }
    
    
}