force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Stock_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Stock_Quantity__c</fullName>
    <label>Stock_Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BookingLWCHelper.cls
public with sharing class BookingLWCHelper {
    
    
    public BookingLWCHelper() {

    }
    @AuraEnabled(cacheable=true)
    public static List<Product__c> searchProduct(String productName){
        return [select Id, Name,Stock_Quantity__c from Product__c where Name like : ('%' + productName + '%')];
    }

    @AuraEnabled(cacheable=true)
    public static List<Booking__c> searchBooking(String bookingName){
        return [SELECT Id, Name, Product__r.Name, Product__r.TotalBooking__c FROM Booking__c WHERE Name LIKE :('%' + bookingName + '%')];

    }


}